# Generated by Django 4.2.5 on 2024-07-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guava', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produksi',
            name='status_produk',
        ),
        migrations.AddField(
            model_name='detailproduksi',
            name='status_produk',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
